name: w2vgender
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'appnope=0.1.0=py36_0'
- !!python/unicode
  'bleach=1.5.0=py36_0'
- !!python/unicode
  'boto=2.47.0=py36_0'
- !!python/unicode
  'bz2file=0.98=py36_0'
- !!python/unicode
  'cycler=0.10.0=py36_0'
- !!python/unicode
  'decorator=4.1.2=py36_0'
- !!python/unicode
  'entrypoints=0.2.3=py36_0'
- !!python/unicode
  'freetype=2.5.5=2'
- !!python/unicode
  'gensim=2.3.0=np113py36_0'
- !!python/unicode
  'html5lib=0.999=py36_0'
- !!python/unicode
  'icu=54.1=0'
- !!python/unicode
  'ipykernel=4.6.1=py36_0'
- !!python/unicode
  'ipython=6.1.0=py36_0'
- !!python/unicode
  'ipython_genutils=0.2.0=py36_0'
- !!python/unicode
  'jedi=0.10.2=py36_2'
- !!python/unicode
  'jinja2=2.9.6=py36_0'
- !!python/unicode
  'jsonschema=2.6.0=py36_0'
- !!python/unicode
  'jupyter_client=5.1.0=py36_0'
- !!python/unicode
  'jupyter_core=4.3.0=py36_0'
- !!python/unicode
  'libpng=1.6.27=0'
- !!python/unicode
  'markupsafe=0.23=py36_2'
- !!python/unicode
  'matplotlib=2.0.2=np113py36_0'
- !!python/unicode
  'mistune=0.7.4=py36_0'
- !!python/unicode
  'mkl=2017.0.3=0'
- !!python/unicode
  'nbconvert=5.2.1=py36_0'
- !!python/unicode
  'nbformat=4.3.0=py36_0'
- !!python/unicode
  'notebook=5.0.0=py36_0'
- !!python/unicode
  'numpy=1.13.1=py36_0'
- !!python/unicode
  'openssl=1.0.2l=0'
- !!python/unicode
  'pandocfilters=1.4.1=py36_0'
- !!python/unicode
  'path.py=10.3.1=py36_0'
- !!python/unicode
  'pexpect=4.2.1=py36_0'
- !!python/unicode
  'pickleshare=0.7.4=py36_0'
- !!python/unicode
  'pip=9.0.1=py36_1'
- !!python/unicode
  'prompt_toolkit=1.0.14=py36_0'
- !!python/unicode
  'ptyprocess=0.5.1=py36_0'
- !!python/unicode
  'pygments=2.2.0=py36_0'
- !!python/unicode
  'pyparsing=2.1.4=py36_0'
- !!python/unicode
  'pyqt=5.6.0=py36_2'
- !!python/unicode
  'python=3.6.2=0'
- !!python/unicode
  'python-dateutil=2.6.1=py36_0'
- !!python/unicode
  'pytz=2017.2=py36_0'
- !!python/unicode
  'pyzmq=16.0.2=py36_0'
- !!python/unicode
  'qt=5.6.2=2'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'requests=2.14.2=py36_0'
- !!python/unicode
  'scikit-learn=0.18.2=np113py36_0'
- !!python/unicode
  'scipy=0.19.1=np113py36_0'
- !!python/unicode
  'setuptools=27.2.0=py36_0'
- !!python/unicode
  'simplegeneric=0.8.1=py36_1'
- !!python/unicode
  'sip=4.18=py36_0'
- !!python/unicode
  'six=1.10.0=py36_0'
- !!python/unicode
  'smart_open=1.5.3=py36_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'terminado=0.6=py36_0'
- !!python/unicode
  'testpath=0.3.1=py36_0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'tornado=4.5.1=py36_0'
- !!python/unicode
  'tqdm=4.14.0=py36_0'
- !!python/unicode
  'traitlets=4.3.2=py36_0'
- !!python/unicode
  'wcwidth=0.1.7=py36_0'
- !!python/unicode
  'wheel=0.29.0=py36_0'
- !!python/unicode
  'xz=5.2.2=1'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.14
  - smart-open==1.5.3
  - treetaggerwrapper==2.2.4

